@echo off
echo Cleaning project...
rd /s /q build
echo Creating directories...
md build\classes
echo Compiling project...
call javac -sourcepath ./src -d build/classes -cp ./libs/commons-lang3-3.11.jar src/ua/com/shyrkov/test/Car.java src/ua/com/shyrkov/test/Test.java src/ua/com/shyrkov/Main.java
echo Executing project...
call java -cp build/classes/;./libs/commons-lang3-3.11.jar;. ua.com.shyrkov.Main