@echo off
@echo Starting maven project...
@echo Cleaning and creating .jar file...
call mvn clean install
cd string_reverse_app
@echo Running application...
java -jar target/string_reverse_app-1.0-SNAPSHOT.jar